### ISSUE TITLE
'freepbx-db' is not accessible, retrying..

### ISSUE THREAD

**Issue by jennso** [tiredofit/docker-freepbx#126]
Hi everyone,

I've tried to troubleshoot this issue for quite sometime, basically if I look at the logs of "freepbx-app" ", I see this message 

[WARN] ** [freepbx] MySQL/MariaDB Server 'freepbx-db' is not accessible, retrying.. (410 seconds so far)

I am running a reverse proxy that has worked very well in the past, I am running on Centos 7

my docker version is: Docker version 19.03.6, build 369ce74a3c
docker-compose version: docker-compose version 1.25.4, build 8d51620a

my docker compose looks like:

```
version: '2'

services:
  freepbx-app:
    container_name: freepbx-app
    image: tiredofit/freepbx
    #links:
     #- freepbx-db
    ports:
     #### If you aren't using a reverse proxy
      #- 80:80
     #### If you want SSL Support and not using a reverse proxy
      #- 443:443
      - 5060:5060
      - 5160:5160
      - 18000-18100:18000-18100/udp
     #### Flash Operator Panel
      - 4445:4445
    volumes:
      - ./certs:/certs
      - ./data:/data
      - ./logs:/var/log
      - ./data/www:/var/www/html
     ### Only Enable this option below if you set DB_EMBEDDED=TRUE
     #- ./db:/var/lib/mysql
     ### You can drop custom files overtop of the image if you have made modifications to modules/css/whatever - Use with care
     #- ./assets/custom:/assets/custom

    environment:
      #- DEBUG_MODE=TRUE
     # - HTTPS_METHOD=nohttps
      - VIRTUAL_HOST=real.hostname.com
      #- VIRTUAL_NETWORK=nginx-proxy_frontend
     ### If you want to connect to the SSL Enabled Container
      #- VIRTUAL_PORT=443
      #- VIRTUAL_PROTO=https
      #- VIRTUAL_PORT=80
      #- LETSENCRYPT_HOST=hostname.example.com
      #- LETSENCRYPT_EMAIL=email@example.com

      - ZABBIX_HOSTNAME=freepbx-app

      - RTP_START=18000
      - RTP_FINISH=18100

     ## Use for External MySQL Server
      - DB_EMBEDDED=FALSE

     ### These are only necessary if DB_EMBEDDED=FALSE
      - DB_HOST=freepbx-db
      - DB_PORT=3306
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=asteriskpass

     ### If you are using TLS Support for Apache to listen on 443 in the container drop them in /certs and set these:
     #- TLS_CERT=cert.pem
     #- TLS_KEY=key.pem

    restart: always
    networks:
      - nginx-proxy_frontend
      - backend

    ### These final lines are for Fail2ban. If you don't want, comment and also add ENABLE_FAIL2BAN=FALSE to your environment
    cap_add:
      - NET_ADMIN
    #privileged: true

  freepbx-db:
    container_name: freepbx-db
    image: tiredofit/mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=asterisk
      - MYSQL_USER=asterisk
      - MYSQL_PASSWORD=asteriskpass
    networks:
      - backend

  freepbx-db-backup:
    container_name: freepbx-db-backup
    image: tiredofit/db-backup
    links:
     - freepbx-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - ZABBIX_HOSTNAME=freepbx-db-backup
      - DB_HOST=freepbx-db
      - DB_TYPE=mariadb
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=asteriskpass
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    networks:
      - backend
    restart: always

networks:
      nginx-proxy_frontend:
         external: true
      backend:
         driver: bridge
```

My nginx proxy looks like this:

```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/conf:/etc/nginx/conf.d

    networks:
      - frontend

networks:
   frontend:
     driver: bridge
```

docker networks looks like this:

```
NETWORK ID          NAME                            DRIVER              SCOPE
cc335f5e56b8        bridge                             bridge              local
19646b475693       freepbx_backend           bridge              local
0b1e9713981c         host                                 host                 local
f7dcb1edb02c          nginx-proxy_frontend    bridge              local
ea4e55e3b72b        none                                null                   local

```

The databse logs just stops at starting [INFO] ** [zabbix] Starting Zabbix Agent

I went inside the containers to ping the other containers and I am able to ping between containers, any help would be really appreciated!
