### ISSUE TITLE
UCP failed to install on first setup

### ISSUE THREAD

**Issue by si458** [tiredofit/docker-freepbx#37]
For some reason the UCP won't install on first setup?

but if you go into the GUI then install it manually from the Module Admin, it then installs without any issues?

```
Module pm2 successfully installed
Updating Hooks...Done
Resetting temporarily repository state
Taking too long? Customize the chown command, See http://wiki.freepbx.org/display/FOP/FreePBX+Chown+Conf
Setting Permissions...
Setting base permissions...Done
Setting specific permissions...
    0 [>---------------------------]
  100 [---------------->-----------]
2018-11-14T15:37:03.515584217Z 
Finished setting permissions
Reloading FreePBX
Successfully reloaded
Edge repository temporarily enabled
No repos specified, using: [standard] from last GUI settings
2018-11-14T15:37:20.291126404Z 
Downloading module 'ucp'
Processing ucp
Downloading...
  200 [---->-----------------------]       0/4260245 [>---------------------------]   0%
  426816/4260245 [==>-------------------------]  10%
  852264/4260245 [=====>----------------------]  20%
 1279080/4260245 [========>-------------------]  30%
 1707264/4260245 [===========>----------------]  40%
 2132712/4260245 [==============>-------------]  50%
 2556792/4260245 [================>-----------]  60%
 2984976/4260245 [===================>--------]  70%
 3410388/4260245 [======================>-----]  80%
 3838608/4260245 [=========================>--]  90%
2018-11-14T15:37:30.282660460Z 
Finished downloading
Extracting...Done
Download completed in 40 seconds
Updating tables ucp_sessions...Done
Home directory [/home/asterisk/.npm] is not writable
Unable to install module ucp:
 - Failed to run installation scripts
Updating Hooks...Done
Resetting temporarily repository state
Taking too long? Customize the chown command, See http://wiki.freepbx.org/display/FOP/FreePBX+Chown+Conf
Setting Permissions...
Setting base permissions...Done
Setting specific permissions...
 4260245/4260245 [============================] 100%    0 [>---------------------------]
  100 [---------------->-----------]
2018-11-14T15:41:14.399881306Z 
Finished setting permissions
```

**Comment by tiredofit** [comment]
Thanks for your contributions earlier today.
`Home directory [/home/asterisk/.npm] is not writable` stands out to me as interesting. Are you running this via docker-compose? I just tried a test install on my end and didn't exhibit that problem.

**Comment by si458** [comment]
your welcome, and more contribs to come :) 

and that's what confused me because yes I am and after a google people say do the 'chown' before you install it, but the init file shows that it does just that, so I'm confused too?

OSX 10.14.1
Docker 18.06.1-ce-mac73

only thing I did differently was I created the yml file manually in visual studio code and run the 'docker compose up' function?

**Comment by tiredofit** [comment]
Wondering if there is something up when creating the exposed folders (./data) and permissions that is acting a strange on Mac. I can boot into a Mac installation a bit later today and see if I experience the same issue.

**Comment by si458** [comment]
this is my docker-compose.yml (in case I've done something wrong but its very basic)
```
version: '2'

services:
  freepbx-app:
    container_name: freepbx-app
    image: tiredofit/freepbx
    ports:
      - 80:80
      - 443:443
      - 5060:5060
      - 5160:5160
      - 18000-18100:18000-18100/udp
    volumes:
      - ./certs:/certs
      - ./data:/data
      - ./logs:/var/log
      - ./data/www:/var/www/html
      - ./db:/var/lib/mysql

    environment: 
      - ENABLE_FAIL2BAN=FALSE
      - ENABLE_FOP=FALSE
      - RTP_START=18000
      - RTP_FINISH=18100
      - DB_EMBEDDED=TRUE
      - UCP_FIRST=FALSE
      - TIMEZONE=Europe/London
      - ENABLE_ZABBIX=FALSE

    restart: always

    privileged: true
```
