### ISSUE TITLE
Synology docker-freepbx install issue

### ISSUE THREAD

**Issue by n1akoue** [tiredofit/docker-freepbx#82]
the container seems to run but I can't connect to 192.168.3.100:25080 (192.168.3.100 is my NAS IP address) on my synology NAS.

Any idea what am I doing wrong?

This is the docker-compose.yml I use: 

```
version: '2'
 services:
  freepbx-app:
    hostname: 192.168.3.100
    container_name: freepbx-app
    image: tiredofit/freepbx
    network_mode: bridge
    ports:
      - 5060:5060/udp
      # - 5160:5160
      - 18000:20000/udp
      - 25080:25080
    volumes:
      - ./certs:/certs
      - ./data:/data
      - ./logs:/www/logs
      - ./data/www:/www/freepbx
    environment:
      - ZABBIX_HOSTNAME=freepbx-app
      - RTP_START=18000
      - RTP_FINISH=18500
      - DB_HOST=192.168.3.100
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=asteriskpass
      - DEBUG_MODE=FALSE      
    restart: always

  freepbx-db:
    container_name: freepbx-db
    image: mariadb:5.5
    network_mode: bridge
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=asterisk
      - MYSQL_USER=asterisk
      - MYSQL_PASSWORD=asteriskpass
```
_______________________________________________________

The error output is the following:

```
sqlclient.target.mk:134: recipe for target 'Release/obj.target/sqlclient/src/binding.o' failed
make: Leaving directory '/var/www/html/admin/modules/ucp/node/node_modules/mariasql/build'
make: *** [Release/obj.target/sqlclient/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack at ChildProcess.emit (events.js:196:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
gyp ERR! System Linux 4.4.59+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/html/admin/modules/ucp/node/node_modules/mariasql
gyp ERR! node -v v12.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mariasql@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mariasql@0.2.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /home/asterisk/.npm/_logs/2019-05-27T01_02_42_819Z-debug.log
[npm-cache] [ERROR] [npm] error running npm install
[npm-cache] [ERROR] error installing dependencies
```
[freepbx-app (1).html.zip](https://github.com/tiredofit/docker-freepbx/files/3222545/freepbx-app.1.html.zip)
