### ISSUE TITLE
asterisk user not being created

### ISSUE THREAD

**Issue by spoctoss** [tiredofit/docker-freepbx#83]
Keep getting this error whenever I tried to startup this container

> No /etc/asterisk/asterisk.conf file detected. Installing...Writing /etc/asterisk/asterisk.conf...Done
> bash: line 0: cd: /home/asterisk/: No such file or directory
> Checking if Asterisk is running and we can talk to it as the 'asterisk' user...Error!

Have tried rebuilding as clean slate several times, also using internal DB.

**Comment by tiredofit** [comment]
Hi Kyle,
Show me your docker-compose section, specifically the volumes section?

**Comment by spoctoss** [comment]
Thanks for getting back to me

here it is

```
    volumes:
      - pbx-certs:/certs
      - pbx-data:/data
      - pbx-log:/var/log
      - pbx-www:/var/www/html
      - pbx-db:/var/lib/mysql

volumes:
  pbx-data:
    external: true
  pbx-www:
    external: true
  pbx-db:
    external: true
  pbx-certs:
    external: true
  pbx-log:
    external: true
```

I do see content in the directories after the initial setup, which I have wiped and tried rebuilding fresh again. Also these volumes are mapped to an NFS share which works for a bunch of other container volumes.
