### ISSUE TITLE
how to configure to run in a subdir?

### ISSUE THREAD

**Issue by junalmeida** [tiredofit/docker-freepbx#9]
is there a way to set this image to run under a subdir, such as http://example.com/pbx

**Comment by tiredofit** [comment]
I just comitted a new release `1.1` which fixes a few bugs that I have encountered in the past few weeks trying to get UCP working, I also added the new environment variable `WEBROOT`. You would use it like so: `WEBROOT=/var/www/html/pbx` which should give you what you are after! Do let me know if it is working for you. The Docker Hub Image will take about 6 hours to appear.

**Comment by junalmeida** [comment]
Thank you for your rapid response. I am going to try this out soon!

**Comment by junalmeida** [comment]
I did a docker-compose down; docker-compose pull, and it downloaded a newer image... then I deleted previous directories, and edited my docker-compose like the following:
```
freepbx-app:
  container_name: freepbx-app
  hostname: mydomain
  image: 'tiredofit/freepbx:latest'
  ports:
    - 5060:5060
    - 5160:5160
    - 18000:20000/udp
    - 805:80
  volumes:
    - ./certs:/certs
    - ./data:/data
    - ./logs:/var/log/asterisk
    - ./data/www:/var/www/html
    - ./db:/var/lib/mysql
    - './configure.sh:/usr/local/bin/configure.sh'
  environment:
    - VIRTUAL_HOST=mydomain
    - VIRTUAL_PORT=80
    - ZABBIX_HOSTNAME=freepbx-app
    - RTP_START=18000
    - RTP_FINISH=20000
    - DB_EMBEDDED=TRUE
    - WEBROOT=/var/www/html/pbx
  restart: always
  cap_add:
    - NET_ADMIN

```

But reaching from the browser I got:

```
Not Found
The requested URL /pbx/ was not found on this server.

Apache/2.4.25 (Debian) Server at
```

**Comment by junalmeida** [comment]
I checked /var/www/html and all files are in the root, there is no pbx dir inside html.

**Comment by tiredofit** [comment]
Nuts. Back to drawing board for me. Will check in in ~ 2 hours with thoughts.

**Comment by tiredofit** [comment]
@junalmeida I just tried a fresh install with the following set in my docker-compose.yml

`      - WEBROOT=/var/www/html/pbx`  

And it seems to be working without problems. If you have an existing install, perhaps take a copy of `/data/www` for backup, and then just create a `/data/www/pbx` moving all files inside of it?

**Comment by junalmeida** [comment]
Maybe I have a tip - amportal.conf: 
```amportal.conf
# FreePBX Web Root Dir
# Default Value: /var/www/html
AMPWEBROOT=/var/www/html
```

**Comment by junalmeida** [comment]
@tiredofit I did a docker-compose down, and deleted all directories, fresh install here I suppose :(

**Comment by junalmeida** [comment]
What I did so far: 
```
root@alma-dev:/data/freepbx# ls
certs  data  db  docker-compose.yml  logs
root@alma-dev:/data/freepbx# docker-compose down
Stopping freepbx-app ... done
Removing freepbx-app ... done
root@alma-dev:/data/freepbx# rm -rf certs data db logs
root@alma-dev:/data/freepbx# ls
docker-compose.yml
root@alma-dev:/data/freepbx# docker-compose up -d
Creating freepbx-app
```

**Comment by junalmeida** [comment]
Then analysing the logs:
 ```
Downloading module 'framework'
freepbx-app    | Processing framework
freepbx-app    | Downloading...
freepbx-app    |         0/11703492 [>---------------------------]   0%
freepbx-app    |   1176464/11703492 [==>-------------------------]  10%
freepbx-app    |   2347472/11703492 [=====>----------------------]  20%
freepbx-app    |   3515728/11703492 [========>-------------------]  30%
freepbx-app    |   4682664/11703492 [===========>----------------]  40%
freepbx-app    |   5857664/11703492 [==============>-------------]  50%
freepbx-app    |   7027416/11703492 [================>-----------]  60%
freepbx-app    |   8192952/11703492 [===================>--------]  70%
freepbx-app    |   9366696/11703492 [======================>-----]  80%
freepbx-app    |  10537704/11703492 [=========================>--]  90%
freepbx-app    |
freepbx-app    | Finished downloading
freepbx-app    | Extracting...Done
freepbx-app    | Download completed in 14 seconds
freepbx-app    | Updating tables admin, ampusers, cronmanager, featurecodes, freepbx_log, freepbx_settings, globals, module_xml, modules, notifications...Done
freepbx-app    | installing files to /var/www/html..done
freepbx-app    | installing files to /var/lib/asterisk/bin..done
freepbx-app    | installing files to /var/lib/asterisk/agi-bin..done
freepbx-app    | Checking for upgrades..
freepbx-app    | No further upgrades necessary
freepbx-app    | framework file install done, removing packages from module
freepbx-app    | file/directory: /var/www/html/admin/modules/framework/amp_conf removed successfully
freepbx-app    | file/directory: /var/www/html/admin/modules/framework/upgrades removed successfully
freepbx-app    | file/directory: /var/www/html/admin/modules/framework/start_asterisk removed successfully
freepbx-app    | file/directory: /var/www/html/admin/modules/framework/install removed successfully
freepbx-app    | file/directory: /var/www/html/admin/modules/framework/installlib removed successfully
```

See the message "installing files to"

So strange that it works for you but not for me :(

**Comment by tiredofit** [comment]
Yes very strange. During my install I get the following:
 Downloading module 'framework'
````
bell-tiredofit-ca-app    | Processing framework
bell-tiredofit-ca-app    | Downloading...
bell-tiredofit-ca-app    |         0/11703492 [>---------------------------]   0%
bell-tiredofit-ca-db     | ** [cron] Starting cron
bell-tiredofit-ca-app    |   1173728/11703492 [==>-------------------------]  10%
bell-tiredofit-ca-app    |   2342016/11703492 [=====>----------------------]  20%
bell-tiredofit-ca-app    |   3514392/11703492 [========>-------------------]  30%
bell-tiredofit-ca-app    |   4682552/11703492 [===========>----------------]  40%
bell-tiredofit-ca-app    |   5853672/11703492 [==============>-------------]  50%
bell-tiredofit-ca-app    |   7028544/11703492 [================>-----------]  60%
bell-tiredofit-ca-app    |   8192952/11703492 [===================>--------]  70%
bell-tiredofit-ca-app    |   9369416/11703492 [======================>-----]  80%
bell-tiredofit-ca-app    | 
bell-tiredofit-ca-app    | Finished downloading
bell-tiredofit-ca-app    |  10533440/11703492 [=========================>--]  90%
bell-tiredofit-ca-app    | Extracting...Done
bell-tiredofit-ca-app    | Download completed in 16 seconds
bell-tiredofit-ca-app    | Updating tables admin, ampusers, cronmanager, featurecodes, freepbx_log, freepbx_settings, globals, module_xml, modules, notifications...Done
bell-tiredofit-ca-app    | installing files to /var/www/html/pbx..done
bell-tiredofit-ca-app    | installing files to /var/lib/asterisk/bin..done
bell-tiredofit-ca-app    | installing files to /var/lib/asterisk/agi-bin..done
````
Can I see a copy of your docker-compose with necessary juicy bits blanked out?

**Comment by junalmeida** [comment]
Sure: 

```
root@alma-dev:/data/freepbx# cat docker-compose.yml
freepbx-app:
  container_name: freepbx-app
  hostname: sis.ferloassessoria.com.br
  image: 'tiredofit/freepbx:latest'
  ports:
    - 5060:5060
    - 5160:5160
    - 18000:20000/udp
    - 805:80
  volumes:
    - ./certs:/certs
    - ./data:/data
    - ./logs:/var/log/asterisk
    #- ./data/www:/var/www/html
    - ./db:/var/lib/mysql
  environment:
    - WEBROOT=/var/www/html/pbx
    - VIRTUAL_HOST=sis.ferloassessoria.com.br
    - VIRTUAL_PORT=80
    #- LETSENCRYPT_HOST=sis.ferloassessoria.com.br
    #- LETSENCRYPT_EMAIL=email@example.com
    - ZABBIX_HOSTNAME=freepbx-app
    - RTP_START=18000
    - RTP_FINISH=20000
    - DB_EMBEDDED=TRUE
  restart: always
  cap_add:
    - NET_ADMIN

```
